name: example
description: A sample command-line application to test web3_storage
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  web3_storage:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
