name: web3_storage
description: Port of web3.storage SDK in Dart
version: 0.0.0
homepage: https://github.com/dart-pacotes/web3.storage
repository: https://github.com/dart-pacotes/web3.storage

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  networking: ^0.0.8
  dartz: ^0.10.1

dev_dependencies:
  flutter_lints: ^2.0.0